# Generated by Django 3.0.8 on 2020-08-25 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200825_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
