# Generated by Django 3.0.8 on 2020-08-26 03:52

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_problems_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[company.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='sol_progress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[company.models.validate_image]),
        ),
    ]
