# Generated by Django 3.0.8 on 2020-08-26 04:19

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200826_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol_progress',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[company.models.validate_image]),
        ),
    ]
